stages:
    - test
    - package
    - deploy

test:
    image: node:14-alpine
    stage: test
    script:
        - npm install
        - npm run lint
        - npm run test:unit -- --coverage --reporters=default --reporters=jest-junit
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - node_modules
    artifacts:
        reports:
            junit: junit.xml
            cobertura: coverage/cobertura-coverage.xml

build-artifacts:
    image: node:14-alpine
    stage: package
    script:
        - npm install
        - npm run build
        - echo "$CI_COMMIT_REF_NAME" > dist/DEPLOY_ID
        - echo "$CI_COMMIT_SHA" >> dist/DEPLOY_ID
        - echo "$CI_JOB_STARTED_AT" >> dist/DEPLOY_ID
    artifacts:
        name: "shutterbug-$CI_COMMIT_REF_NAME"
        public: true
        paths:
            - dist
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - node_modules

